### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by rishu595** [radi0sus/orca_orb#1]
Hi.
When I am running the script, I am getting the following error:
Traceback (most recent call last):
  File "C:\Users\khuranr\Downloads\orca_orb-master\orca_orb-master\orca_orb.py", line 413, in <module>
    oall=pd.DataFrame(os) # initialize DataFrame for oall
NameError: name 'os' is not defined. Did you mean: 'ops'?

could you please help me what I am missing here?

Best,
Rishu

**Comment by radi0sus** [comment]
I have to admit that I haven't worked on the script for a long time. But after testing it today, it seemed fine. 
Maybe the ORCA output has changed from 4 to 5? Some of the instructions in the script could be deprecated (especially pandas)? You should also check whether your output contains the necessary information (LOEWDIN REDUCED ORBITAL POPULATIONS PER MO).
